name: flutter_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependency_overrides:
  intl: ^0.18.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  rflutter_alert: ^2.0.4
  get_it: ^7.3.0
  get_it_mixin: ^4.1.1
  jwt_decode: ^0.3.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  skeletons: ^0.0.3
  carousel_slider: ^4.1.1
  get: ^4.6.5
  country_code_picker: ^3.0.0
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.4
  flutter_share: ^2.0.0
  jiffy: ^6.2.1
  connectivity_plus: ^4.0.1
  flutter_multi_formatter: ^2.5.7
  geocoding: ^2.0.4
  google_nav_bar: ^5.0.6
  indexed: ^0.0.8
  flutter_widget_from_html_core: ^0.14.5
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.2
  loader_overlay: ^2.2.0
  font_awesome_flutter: ^10.5.0
  ionicons: ^0.2.2
  feather_icons: ^1.2.0
  image_cropper: ^4.0.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.14.5
  fwfh_webview: 0.14.2
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.2
  html: ^0.15.4
  flutter_launcher_icons: ^0.13.1
  file_picker: ^6.1.1
  in_app_purchase: ^3.0.7
  rate_limiter: ^1.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^17.2.2
  flutter_app_badger: ^1.5.0
  flutter_vector_icons: ^2.0.0
  easy_localization: ^3.0.3
  social_login_buttons: ^1.0.7
  fwfh_just_audio: ^0.14.3
  syncfusion_flutter_pdfviewer: ^20.4.54



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/icon/
    - assets/images/icon-tab/

  fonts:
    - family: SnigletBold
      fonts:
        - asset: assets/fonts/Sniglet-ExtraBold.ttf

    - family: Sniglet
      fonts:
        - asset: assets/fonts/Sniglet-Regular.ttf

    - family: SnigletExtraBold
      fonts:
        - asset: assets/fonts/Sniglet ExtraBold 800.ttf

    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: poppins-extraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf